### ISSUE TITLE
Where does the statistics data of success_query_all come from?

### ISSUE THREAD

**Issue by machanic** [ZiangYan/subspace-attack.pytorch#1]
The `success_query_all` is initialized as `success_query_all = torch.zeros_like(query_all)` in
https://github.com/ZiangYan/subspace-attack.pytorch/blob/master/attack.py#L264

But after initialization,  it never changes, in the final statistics result report as shown in :
https://github.com/ZiangYan/subspace-attack.pytorch/blob/master/attack.py#L514

How does `success_query_all` change to the real statistics  result?

**Comment by ZiangYan** [comment]
Hi, please check

https://github.com/ZiangYan/subspace-attack.pytorch/blob/master/attack.py#L484-L489
