### ISSUE TITLE
Can you provide config for imagenet under L2 distance constrain?

### ISSUE THREAD

**Issue by jiangyangzhou** [ZiangYan/subspace-attack.pytorch#2]

**Comment by ZiangYan** [comment]
We have never run imagenet L2 experiments, and so we do not know which hyper-parameter configuration is good in this case.

**Comment by jiangyangzhou** [comment]
Else, can you provide test image set for imagenet in your case

**Comment by jiangyangzhou** [comment]
Do you use data prior like Bandit-TD?

**Comment by ZiangYan** [comment]
For test images, please see our experiment logs for more details. 

For bandit-TD style data prior, please check delta_size at https://github.com/ZiangYan/subspace-attack.pytorch/blob/master/attack.py#L37

**Comment by jiangyangzhou** [comment]
It seems you set delta=0 as default, it means no data prior,  and you got less query times than Bandit-td in your experiment.   But  you can add data prior, this thick should get better performance.

**Comment by ZiangYan** [comment]
Please see our experiment logs for detailed hyper-parameters, including the values of delta_size for all numbers reported in our paper.
