### ISSUE TITLE
The bug report of calculating attack failure rate 

### ISSUE THREAD

**Issue by machanic** [ZiangYan/subspace-attack.pytorch#4]
I found a bug of computing the `attack failure rate `, because in 
https://github.com/ZiangYan/subspace-attack.pytorch/blob/master/attack.py#L512
you directly use `not_done_all.mean().item()` as the failure rate.
However, due to bandits attack's code:
https://github.com/MadryLab/blackbox-bandits/blob/master/src/main.py#L178

You miss the case that some benign images are already misclassified by the classifier before attacking. The `attack success rate` or `failure rate` should use the correctly classified images to calculate. You must remove/filter these misclassified clean images in the computation. Thus, your paper's failure rate is not correct strictly speaking, unless all 1000 images are already correctly classified by the victim model.

Also, the code of https://github.com/thu-ml/Prior-Guided-RGF/blob/master/attack.py#L372
supports my suggestion.

**Comment by ZiangYan** [comment]
There is a subtle difference between ```not_done_all.mean().item()``` and attack failure rate.

Although our script only print ```not_done``` to log, when we were writing the paper we also noticed the difference and re-calculated correct attack failure rates using saved pth files.
